In [6]:
import pandas as pd

df = pd.read_csv("data/raw/dataset_projet_ecommerce.csv")
df.head()

,ClientID,Nom,Prénom,Email,Téléphone,Adresse,Ville,CodePostal,Pays,DateNaissance,...,CatégorieProduitPréféré,FréquenceAchatMensuel,PanierMoyen,ScoreFidélité,NombreRemboursements,MontantTotalRemboursé,AvisClient,AbonnementNewsletter,TypePaiementFavori,StatutCompte
0,d34f9cab-5d14-469f-aa80-c0146f3b93c7,Walters,Christopher,vickie68@hotmail.com,818-767-2351x61325,"Unit 4018 Box 5177, DPO AA 69318",Lauratown,45532,Antigua and Barbuda,1996-09-15,...,Sport,6,165.43,85,1,11.68,Neutre,True,Paypal,Inactif
1,d9b374f9-8cec-4ae7-9137-c1d930d0aae0,Weaver,Linda,mackrenee@rodriguez.com,892-112-2129x2425,"19114 Ryan Grove, East Miranda, MO 40887",Herreraview,6486,Belize,2000-01-11,...,Électronique,6,71.01,15,2,152.13,Satisfait,False,Carte bancaire,Actif
2,72855e63-d98e-42e9-a10f-d9e4fac6e82f,Odonnell,Julie,alexis55@gmail.com,001-505-122-4709x1134,"610 Donna Neck, Lake Paulmouth, MA 32585",Lake Erictown,85092,Andorra,1961-06-07,...,Alimentation,9,104.43,10,5,342.60,Satisfait,False,Cryptomonnaie,Suspendu
3,3fcb2796-9692-4fcf-affb-0100d9a74ae1,Clark,Charles,jenniferschmidt@yahoo.com,(101)867-7119,"177 Anne Bridge, Perezberg, MA 91533",New Andrewton,87164,Samoa,1970-11-19,...,Alimentation,5,161.23,4,0,0.00,Mécontent,False,Virement,Actif
4,50b21cc8-6f68-45c5-9b75-335ef55b41b2,Martinez,David,hmiddleton@mendoza.com,(820)441-6404x9218,"59971 Haynes Glens Apt. 520, Meganhaven, MN 92380",Rodriguezport,53640,Burkina Faso,1946-02-26,...,Mode,1,87.27,6,0,0.00,Mécontent,True,Cryptomonnaie,Inactif

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ClientID                 1000 non-null   object
 1   Nom                      1000 non-null   object
 2   Prénom                   1000 non-null   object
 3   Email                    1000 non-null   object
 4   Téléphone                1000 non-null   object
 5   Adresse                  1000 non-null   object
 6   Ville                    1000 non-null   object
 7   CodePostal               1000 non-null   int64
 8   Pays                     1000 non-null   object
 9   DateNaissance            1000 non-null   object
 10  Âge                      1000 non-null   int64
 11  Sexe                     1000 non-null   object
 12  NuméroCarteCrédit        1000 non-null   int64
 13  TypeCarteCrédit          1000 non-null   object
 14  DateExpirationCarte      1000 non-null   object
 15  SoldeCompte              1000 non-null   float64
 16  TypeClient               1000 non-null   object
 17  NombreAchats             1000 non-null   int64
 18  MontantTotalAchats       1000 non-null   float64
 19  DernierAchat             1000 non-null   object
 20  ProduitPréféré           1000 non-null   object
 21  CatégorieProduitPréféré  1000 non-null   object
 22  FréquenceAchatMensuel    1000 non-null   int64
 23  PanierMoyen              1000 non-null   float64
 24  ScoreFidélité            1000 non-null   int64
 25  NombreRemboursements     1000 non-null   int64
 26  MontantTotalRemboursé    1000 non-null   float64
 27  AvisClient               1000 non-null   object
 28  AbonnementNewsletter     1000 non-null   bool
 29  TypePaiementFavori       1000 non-null   object
 30  StatutCompte             1000 non-null   object
dtypes: bool(1), float64(4), int64(7), object(19)
memory usage: 235.5+ KB

In [8]:
df.describe()

,CodePostal,Âge,NuméroCarteCrédit,SoldeCompte,NombreAchats,MontantTotalAchats,FréquenceAchatMensuel,PanierMoyen,ScoreFidélité,NombreRemboursements,MontantTotalRemboursé
count,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,50576.295000,55.466000,3.992066e+17,2619.975090,10.487000,2608.90697,4.879000,238.349630,51.484000,2.570000,262.85884
std,29093.854764,21.021816,1.288862e+18,1443.421728,5.890036,2287.38721,3.260213,150.407597,28.691583,1.705875,248.75859
min,525.000000,18.000000,6.042067e+10,2.680000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,23961.250000,37.000000,1.800195e+14,1385.430000,6.000000,780.31750,2.000000,105.547500,27.000000,1.000000,50.26500
50%,52513.000000,56.000000,3.505393e+15,2734.705000,11.000000,1877.64000,5.000000,235.540000,52.000000,3.000000,192.24000
75%,76447.000000,73.000000,4.610821e+15,3865.872500,16.000000,4011.89750,8.000000,370.295000,76.000000,4.000000,394.25250
max,99876.000000,91.000000,4.998787e+18,4994.880000,20.000000,9752.86000,10.000000,499.830000,100.000000,5.000000,995.98000

In [9]:
df.isnull().sum()

ClientID                   0
Nom                        0
Prénom                     0
Email                      0
Téléphone                  0
Adresse                    0
Ville                      0
CodePostal                 0
Pays                       0
DateNaissance              0
Âge                        0
Sexe                       0
NuméroCarteCrédit          0
TypeCarteCrédit            0
DateExpirationCarte        0
SoldeCompte                0
TypeClient                 0
NombreAchats               0
MontantTotalAchats         0
DernierAchat               0
ProduitPréféré             0
CatégorieProduitPréféré    0
FréquenceAchatMensuel      0
PanierMoyen                0
ScoreFidélité              0
NombreRemboursements       0
MontantTotalRemboursé      0
AvisClient                 0
AbonnementNewsletter       0
TypePaiementFavori         0
StatutCompte               0
dtype: int64